In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\Users\david\OneDrive\Desktop\trainee dados scitec\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\david\OneDrive\Desktop\trainee dados scitec\.venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\david\OneDrive\Desktop\trainee dados scitec\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\david\OneDrive\Desktop\trainee dados scitec\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\david\OneDrive\Desktop\trainee dados scitec\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\Users\david\OneDrive\Desktop\trainee dados scitec\.venv\Lib\site-packages (24.0.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("popular_people.csv")
df

,name,gender,known_for_department,original_name,popularity
0,Eric Larson,2,Visual Effects,Eric Larson,47.9780
1,Robert Middlemass,2,Acting,Robert Middlemass,47.8017
2,María Vaner,1,Acting,María Vaner,47.2016
3,Carl Wharton,2,Acting,Carl Wharton,36.3365
4,Victor Moore,2,Acting,Victor Moore,35.9181
...,...,...,...,...,...
9975,Tamu Blackwell,1,Acting,Tamu Blackwell,1.0432
9976,Yoshio Urasawa,2,Writing,浦沢義雄,1.1777
9977,Miko Hughes,2,Acting,Miko Hughes,1.5346
9978,Phoebe Fox,1,Acting,Phoebe Fox,1.1656
9979,Debora Calì,1,Acting,Debora Calì,1.2658

dropar uma coluna

In [5]:
df = df.drop(columns = ["original_name", "gender"])
df

                   name known_for_department  popularity
0           Eric Larson       Visual Effects     47.9780
1     Robert Middlemass               Acting     47.8017
2           María Vaner               Acting     47.2016
3          Carl Wharton               Acting     36.3365
4          Victor Moore               Acting     35.9181
...                 ...                  ...         ...
9975     Tamu Blackwell               Acting      1.0432
9976     Yoshio Urasawa              Writing      1.1777
9977        Miko Hughes               Acting      1.5346
9978         Phoebe Fox               Acting      1.1656
9979        Debora Calì               Acting      1.2658

[9980 rows x 3 columns]

para ler as primeiras linhas do banco de dados

In [18]:
df.head()

                name known_for_department  popularity
0        Eric Larson       Visual Effects   47.978001
1  Robert Middlemass               Acting   47.801701
2        María Vaner               Acting   47.201599
3       Carl Wharton               Acting   36.336498
4       Victor Moore               Acting   35.918098

para ver quanto uma tabela ocupa de memoria, faz um raio x completo, mostrando a estrutura interna

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9980 entries, 0 to 9979
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  9980 non-null   string
 1   known_for_department  9975 non-null   str
 2   popularity            9980 non-null   float32
dtypes: float32(1), str(1), string(1)
memory usage: 382.2 KB

df.info faz uma estimativa rapida, para fazer uma busca profunda de toda a estrutura

In [17]:
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 9980 entries, 0 to 9979
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  9980 non-null   string
 1   known_for_department  9975 non-null   str
 2   popularity            9980 non-null   float32
dtypes: float32(1), str(1), string(1)
memory usage: 382.2 KB

acima da para ver a diferença, quando antes apontava 312kb agora apontou 1,8mb

para ir direto ao ponto e mostrar quantos bytes cada coluna individual está gastando na memória RAM.

In [13]:
df.memory_usage(deep=True)

Index                      132
name                    208924
known_for_department    142443
popularity               79840
dtype: int64

para saber os dados que foram escritos em uma coluna, sem repetição

In [ ]:
df["gender"].unique()

In [9]:
df["known_for_department"].unique()

<ArrowStringArray>
[   'Visual Effects',            'Acting',         'Directing',
           'Writing',           'Editing',        'Production',
          'Lighting',             'Sound',            'Camera',
              'Crew',               'Art',           'Creator',
 'Costume & Make-Up',                 nan]
Length: 14, dtype: str

para tratar os dados e alterar o tipo da variavel

In [ ]:
df["gender"] = df["gender"].map({0: "Not Set", 1: "Female", 2: "Male", 3: "Non-Binary"}).astype("category")

In [10]:
df["known_for_department"].map({"Acting": "Arts", "Directing": "Arts", "Production": "Arts", "Writing": "Arts", "Creator": "Arts", "Sound": "Technical", "Camera": "Technical", "Visual Effects": "Technical", "Editing": "Technical", "Art": "Technical", "Costume & Make-Up": "Technical", "Crew": "Technical", "Lighting": "Technical"}).fillna("Other").astype("category")

0       Technical
1            Arts
2            Arts
3            Arts
4            Arts
          ...
9975         Arts
9976         Arts
9977         Arts
9978         Arts
9979         Arts
Name: known_for_department, Length: 9980, dtype: category
Categories (3, str): ['Arts', 'Other', 'Technical']

In [14]:
df["name"] = df["name"].astype("string[pyarrow]")

In [15]:
df["popularity"] = df["popularity"].astype("float32")

para descrever a qntd de dados, media, valor min, valor max em cada coluna

In [21]:
df.describe(include="all")

              name known_for_department   popularity
count         9980                 9975  9980.000000
unique        7662                   13          NaN
top     Shawn Levy               Acting          NaN
freq             4                 9320          NaN
mean           NaN                  NaN     2.123684
std            NaN                  NaN     1.893017
min            NaN                  NaN     0.578400
25%            NaN                  NaN     1.358150
50%            NaN                  NaN     1.647000
75%            NaN                  NaN     2.209725
max            NaN                  NaN    47.978001

Para salvar o novo arquivo otimizado em csv

In [ ]:
df.to_excel("popular_people_otimizado.xlsx", index=False)

In [20]:
df.to_csv("popular_people_otimizado.csv", index=False)